name: foil
description: >
  Wrap a widget with Foil, providing a rainbow shimmer
  that twinkles as the accelerometer moves as well as
  tons of neat gradient features.
version: 0.9.0+1
repository: https://github.com/Zabadam/foil
issue_tracker: https://github.com/Zabadam/foil/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  spectrum: 
    path: ../spectrum
  sensors_plus: ^4.0.2



flutter: null
